### ISSUE TITLE
write the docker-superset tech documentation

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgot4d.github.io#21]
Should be a more polished version of the `README` in the `docker-superset` repo

See https://github.com/DalgoT4D/docker-superset/issues/54

**Comment by himanshudube97** [comment]
@fatchat 
[This](https://docs.google.com/document/d/1l24tphe8iv1dQkIZ4s4xQIQu1vCB33YLCrjwSvWj5wA/edit?usp=sharing)
 is the doc for the superset tech documentation.

**Comment by fatchat** [comment]
Nice, could you
- read and accept my suggestions
- remove the different colors for headings etc
- use a uniform font
-
